### ISSUE TITLE
цель приложения не совсем ясна

### ISSUE THREAD

**Issue by AlexFundorin** [qwert2603/VK-Mutual-Groups#1]
Много лет уже было интересно, на какие группы подписаны мои друзья-меломаны, чтобы тоже подписаться на эти группы. ВК не позволяет увидеть такие группы.
Думал, это приложение поможет. Оказалось же, что оно умеет только показывать общие группы, на которые вы оба уже подписаны. 
Жаль. Было бы полезно открыть для себя новые группы, которые пользуются популярностью у друзей.

**Comment by qwert2603** [comment]
здравствуйте!
исходя из названия ("**Общие** группы ВК"), приложение и должно показывать только те группы, на которые подписаны и Вы, и Ваш друг.
Отображение групп, которые пользуются популярностью у друзей, не входит в функции этого приложения. Вы можете поискать что-нибудь подходящее на Google Play.
